# Generated by Django 5.2.5 on 2025-08-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(upload_to='avaliacoes/')),
            ],
        ),
    ]
