# Generated by Django 5.2.5 on 2025-09-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(upload_to='testimonials/')),
            ],
        ),
        migrations.RenameModel(
            old_name='cadastros',
            new_name='Contacts',
        ),
        migrations.DeleteModel(
            name='Avaliacoes',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.DeleteModel(
            name='produtos',
        ),
    ]
